branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

services:
  - docker

language: cpp

env:
  global:
    - secure: "rfE48+aRZyO6KgAaSABmZ6zb1Vvzf1OC2333CDHyt9lvIrHD0fJk0jE9Fi+Kfw+ugkjGZ9+7L8jOMYrHxoSVMvpg4Zu2/R3wjhENykKLIfEyhtkVsOr6ZbeVcTnvmzOcHoAd6jb8X97QhQy2kvruZC0OykEMsYYT0uNmYkD0FzFktSJXP93o1YTDeShDUCGDgnG7gbnKbArVI0ma/vLlQ2qlgidj0f2uXtw7lKichCAZvcJExUFu10lxjo6TWi4rbbK0iS9Em1UGLpcT6D0jr5OTlBxAx4hRM8MqKVZw5RM33pktCi9KtWO7p+QMTwo/0OWLMs0WY0wkhMY1o1PLDayG3b4DUwwiTfpabFCq5RaMhdw/PXxpkhFKYzyEtwNjV6hVx4wZCOBgebiaVZyuVdqiHjU26ykzrvBgtPA1BVHwO3VB5fVYvHxE4x57IAcIeMYt0hvWPuqH/aFP3IwD+dIHDm4R6iBbprQ5rf7W2Q+JdzdwVkJTg47YgzgufeyUtK9bL+97yF6jy19TVD139lJdblFFKpcdE86cCPEWKnaVq9E4a8cPxN1XJmbQCe97+oo1ZRb0eALbuCEb63GP00qgzE3i22O6ymfJgQoBqZwBCF9ZUjkzQcDEDj9Jc5HfHpuv4YeWiooMgqbh8nypZ7iaVSyYHQu3BREVC1H799o="
    - secure: "CFTyzfMGhxIDGWhT1ZJzDCMWSOEfjsMDzlOLPDVFrXcNFwtIj5IdK/BhIIWA12fJYo3F+B0APmF8cPXAc1UNPba3/5hyyF7nLRoLurDu+uD+KyKVIdO67L3Of76pXZGEZpv8t2z6NfOQqMN6qRks9Y/Hc+YQNu+UF9t1OJZfSWf+dnz7aiXQRa+dRaSEu8R3ZOCxJyNTnNhsFsMmvqUcdjTr1E9N8B7DD6Ct9xvSk5F7FSr1/BOgOe5V/HST8JD557Z0RXcudre6ks3f6uBH6yOheegfAXFIrYv/CaOUiChOE8mL19jZdMgbuQeJlo0Ny+ga6GW079PIDE0mjfIiTTpFOnw09YwFkh46euukilFj6OY5Oqo3kyYBSFwxsfmZk5ogf1DTnpaRv4Wwd2vyE66VgN14qRAucfmCaTRU5Kt2/ks+M4KVWnOmriBQWaUlH/uB7X6Saq0e2/J4ck/XShWuVeYHEpQ7YjJWi3oksmjvGhyEro8tUOUIghF9xSNQdZow0xgIqkUy1ntwbN+NYlaLbRRwx16ICZ4D8KHk1otohQssiw7P2zOKYyZdBQIif9KX0idwifXbMjr3h+RtQOA4eyN9nj8/PdcyXg2hdRQxJjrK1SLfzXRvR6P/LxthMPdj6dItM4nsAWaUrYfxi9SsZllJPOUakfuZ8IC8D9Q="

script:
  - make build test

after_success:
  - >
    [ "${TRAVIS_TEST_RESULT}" == 0 ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" != "master" ] &&
      (docker login --username $DOCKER_USER --password $DOCKER_PASS; \
      docker build -f Dockerfile -t imega/mysql:$TRAVIS_BRANCH . ; \
      docker push imega/mysql:$TRAVIS_BRANCH)

  - >
    [ "${TRAVIS_TEST_RESULT}" == 0 ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] &&
      (docker login --username $DOCKER_USER --password $DOCKER_PASS; \
      docker build -f Dockerfile -t imega/mysql-test . ; \
      docker push imega/mysql-test)
